INSERT INTO USERS (NAME) VALUES ('Rui');
INSERT INTO USERS (NAME) VALUES ('Beatriz');

INSERT INTO EXPENSE(EXPENSE_TIMESTAMP, AMOUNT, DESCRIPTION) VALUES ('2023-05-04', 943, 'Disneyland Tickets');
INSERT INTO EXPENSE(EXPENSE_TIMESTAMP, AMOUNT, DESCRIPTION) VALUES ('2023-07-24', 6, null);
