CREATE TABLE USERS(
  USER_ID BIGSERIAL PRIMARY KEY,
  NAME VARCHAR(16) NOT NULL
);

CREATE TABLE EXPENSE(
  EXPENSE_ID BIGSERIAL PRIMARY KEY,
  EXPENSE_TIMESTAMP DATE NOT NULL,
  AMOUNT BIGINT NOT NULL,
  DESCRIPTION VARCHAR(64)
);
